version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - db

volumes:
  db_data:
